---
title : 'graph'
output : html_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# load packages
library(ggplot2)

source.dir <- 'C:/Users/Will/Dropbox/Dissertation/Journal Paper/'
# source.dir <- 'F:/Dissertation/Journal Paper/'

setwd(source.dir)

theme_set(theme_gray() + theme(axis.text = element_text(color = 'black', size = 11), text = element_text(color = 'black', family = 'serif', size = 11)))

```

# graph.Rmd
#
# William John Zywiec
# The George Washington University
#
# ...

```{r}

year <- c(
  1945, 1945, 1945, 1946, 1949, 1950, 1951, 1951, 1952, 1952,
  1952, 1953, 1953, 1954, 1954, 1954, 1955, 1956, 1956, 1957,
  1957, 1958, 1958, 1958, 1958, 1958, 1959, 1960, 1960, 1960,
  1961, 1961, 1962, 1962, 1961, 1961, 1962, 1962, 1963, 1963,
  1963, 1963, 1964, 1965, 1965, 1965, 1965, 1968, 1968, 1968,
  1968, 1970, 1971, 1971, 1978, 1978, 1983, 1997, 1997, 1999)

accident <- c(
  'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor',
  'reactor', 'reactor', 'process', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor',
  'process', 'reactor', 'reactor', 'process', 'process', 'process', 'process', 'reactor', 'reactor', 'process',
  'reactor', 'reactor', 'reactor', 'reactor', 'process', 'process', 'process', 'process', 'reactor', 'reactor',
  'process', 'process', 'process', 'reactor', 'reactor', 'process', 'process', 'reactor', 'reactor', 'reactor',
  'process', 'process', 'reactor', 'reactor', 'process', 'process', 'reactor', 'reactor', 'process', 'process')

country <- c(
  'US', 'US', 'US', 'US', 'US', '--', 'US', 'US', 'US', 'US',
  '--', '--', '--', 'US', 'US', 'US', 'US', 'US', 'US', 'US',
  '--', 'US', '--', 'US', 'US', '--', 'US', 'US', '--', '--',
  'US', 'US', 'US', 'US', 'US', '--', 'US', '--', 'US', '--',
  '--', '--', 'US', 'US', '--', '--', '--', 'US', 'US', '--',
  '--', '--', '--', '--', 'US', '--', '--', '--', '--', '--')

df <- data.frame(year, accident, country)

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = country)) +
  scale_fill_manual(labels = c('outside the United States', 'in the United States'), values = c('#C0C0C0', '#FC4E07')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  ylab('criticality accidents')

ggsave('fig-1.png', dpi = 320, height = 3, width = 6.5)

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = forcats::fct_rev(accident))) +
  scale_fill_manual(labels = c('critical experiments and research reactors', 'production facilities'), values = c('#C0C0C0', '#FC4E07')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  ylab('criticality accidents')

ggsave('fig-2.png', dpi = 320, height = 3, width = 6.5)

df <- df[which(df$accident == 'process'), ]

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = country)) +
  scale_fill_manual(labels = c('outside the United States', 'in the United States'), values = c('#C0C0C0', '#FC4E07')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5), limits = c(0, 5)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  ylab('criticality accidents') +

ggsave('fig-3.png', dpi = 320, height = 3, width = 6.5)

```

```{r}

keff <- c(seq(0.05, 0.95, 0.05), 0.99, 0.999)
M <- sapply(keff, function(x) 1/(1-x))

df <- data.frame(keff, M)

ggplot(df, aes(x = keff, y = M)) +
  geom_line() +
  geom_point() +
  xlab(bquote(k[eff])) +
  scale_y_log10() +

ggsave('fig-x.png', dpi = 320, height = 3.2, width = 6.5)

```

```{r}

df <- read.csv(paste0(source.dir, 'fig-4-data.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = EALF, y = keff, ymin = keff - sd, ymax = keff + sd)) +
  geom_point(size = 0.8) +
  geom_linerange(size = 0.2) +
  geom_smooth(color = '#FC4E07', se = FALSE, size = 0.8, span = 0.11) +
  scale_x_log10(breaks = c(1e-07, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1e+00), minor_breaks = c(1e-07, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1e+00)) +
  scale_y_continuous(breaks = seq(0.99, 1.04, 0.01), minor_breaks = seq(0.99, 1.04, 0.01)) +
  xlab('energy of average neutron lethargy causing fission (MeV)') +
  ylab(bquote(k[eff]))

ggsave('fig-4.png', dpi = 320, height = 3.6, width = 6.5)

```

```{r}

# load packages
library(metR)

df <- read.csv(paste0(source.dir, 'fig-5-data.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = radius, y = mass, z = keff)) +
  geom_contour(color = '#A9A9A9', size = 0.6) +
  geom_text_contour(aes(z = keff), family = 'serif', size = 3.5, stroke = 0.1) +
  xlab('radius (cm)') +
  ylab('plutonium mass (g)')

ggsave('fig-5.png', dpi = 320, height = 3.6, width = 6.5)

```

```{r}

library(gridExtra)

mass.cpt <- readRDS('mass.RData')

df.1 <- as.data.frame(mass.cpt[[1]][[1]])
df.2 <- as.data.frame(mass.cpt[[2]][[1]])
df.3 <- as.data.frame(mass.cpt[[3]][[1]])
df.4 <- as.data.frame(mass.cpt[[4]][[1]])
df.5 <- as.data.frame(mass.cpt[[5]][[1]])
df.6 <- as.data.frame(mass.cpt[[6]][[1]])

x <- c(1:1001)

colnames(df.1) <- c('y')
colnames(df.2) <- c('y')
colnames(df.3) <- c('y')
colnames(df.4) <- c('y')
colnames(df.5) <- c('y')
colnames(df.6) <- c('y')

p.1 <- ggplot(df.1, aes(x, y)) + ggtitle('large sample') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)
p.2 <- ggplot(df.2, aes(x, y)) + ggtitle('machining') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)
p.3 <- ggplot(df.3, aes(x, y)) + ggtitle('metallurgy') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)
p.4 <- ggplot(df.4, aes(x, y)) + ggtitle('small sample') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)
p.5 <- ggplot(df.5, aes(x, y)) + ggtitle('solution') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)
p.6 <- ggplot(df.6, aes(x, y)) + ggtitle('waste') + geom_line() + scale_x_log10(breaks = c(1, 10, 100, 1000), minor_breaks = c(1, 10, 100, 1000)) + scale_y_continuous(breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), minor_breaks = c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5), limits = c(0, 0.5)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('Pu mass (g)') + ylab(NULL)

grid.arrange(p.1, p.2, p.3, p.4, p.5, p.6, nrow = 2)

ggsave('fig-7.png', plot = grid.arrange(p.1, p.2, p.3, p.4, p.5, p.6, nrow = 2), dpi = 320, height = 3.6, width = 6.5)

```

```{r}

z <- c(-2, 0, 2)
y <- c(0, 0, 2)

df <- data.frame(z, y)

ggplot(df, aes(x = z, y =y )) +
  coord_cartesian(xlim = c(-1, 1), ylim = c(0, 1)) +
  geom_line() +
  scale_x_continuous('z', breaks = 0, expand = c(0, 0), minor_breaks = 0) +
  scale_y_continuous('g(z) = max{0, z}', breaks = 0, expand = c(0, 0), minor_breaks = 0)

ggsave('fig-8.png', dpi = 320, height = 2.5, width = 5)

```

```{r}

df.1 <- read.csv(paste0(source.dir, 'nn-1.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
df.2 <- read.csv(paste0(source.dir, 'nn-2.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df.2, aes(x = layers, y = val.mae)) +
  geom_point(aes(color = 'validation error (not optimized)')) +
  geom_line(data = df.1, aes(x = layers, y = val.mae, color = 'validation error')) +
  geom_point(data = df.1, aes(x = layers, y = val.mae, color = 'validation error')) +
  scale_color_manual('', breaks = c('validation error', 'validation error (not optimized)'), values = c('#FC4E07', '#808080')) +
  scale_x_continuous('hidden layers', breaks = 1:7, minor_breaks = 1:7) +
  scale_y_continuous(bquote(mean ~ absolute ~ error ~ (k[eff])), breaks = c(4e-04, 1e-03, 1e-04), minor_breaks = c(4e-04, 1e-03, 1e-04), limits = c(4e-04, 1e-03)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank())

ggsave('fig-9.png', dpi = 320, height = 3.4, width = 6.5)

```

```{r}

df <- read.csv(paste0(source.dir, 'nn-1.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = layers)) +
  geom_line(aes(y = mae, color = 'training error')) +
  geom_point(aes(y = mae, color = 'training error')) +
  geom_line(aes(y = val.mae, color = 'validation error')) +
  geom_point(aes(y = val.mae, color = 'validation error')) +
  scale_color_manual('', breaks = c('training error', 'validation error'), values = c('black', '#FC4E07')) +
  scale_x_continuous(breaks = 1:7, minor_breaks = 1:7) +
  scale_y_continuous(breaks = seq(3e-04, 1e-03, 1e-04), minor_breaks = c(3e-04, 1e-03, 1e-04), limits = c(3e-04, 1e-03)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  xlab('hidden layers') +
  ylab(bquote(mean ~ absolute ~ error ~ (k[eff])))

ggsave('fig-10.png', dpi = 320, height = 3.4, width = 6.5)

```

```{r}

library(reshape)

df <- read.csv(paste0(source.dir, 'fig-11-data.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
df <- melt(df)
names(df)[3] <- 'error'

ggplot(df, aes(x = optimizer, y = error, fill = variable)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  scale_fill_manual('legend', labels = c('training error', 'validation error'), values = c('mae' = 'black', 'val.mae' = '#FC4E07')) +
  scale_y_continuous(breaks = seq(0, 0.006, 0.001), minor_breaks = seq(0, 0.006, 0.001)) +
  theme(axis.title.x = element_blank(),
    legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  ylab(bquote(mean ~ absolute ~ error ~ (k[eff])))

ggsave('fig-11.png', dpi = 320, height = 3.4, width = 6.5)

```

```{r}

df <- read.csv(paste0(source.dir, 'fig-12-data.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = lr)) +
  geom_line(aes(y = val.mae, color = 'validation error')) +
  geom_point(aes(y = val.mae, color = 'validation error')) +
  geom_line(aes(y = mae, color = 'training error')) +
  geom_point(aes(y = mae, color = 'training error')) +
  scale_color_manual('', breaks = c('training error', 'validation error'), values = c('black', '#FC4E07')) +
  scale_x_continuous(breaks = seq(0, 0.006, 0.001)) +
  scale_y_continuous(breaks = c(2e-04, 4e-04, 6e-04, 8e-04, 1e-03), limits = c(1e-04, 1e-03)) +
  theme(legend.position = 'bottom',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 10),
    legend.title = element_blank()) +
  xlab('learning rate') +
  ylab(bquote(mean ~ absolute ~ error ~ (k[eff])))

ggsave('fig-12.png', dpi = 320, height = 3.4, width = 6.5)

```

```{r}

df <- read.csv(paste0(source.dir, 'test-mae.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = 1:50)) +
  geom_line(aes(y = test.mae)) +
  geom_point(aes(y = test.mae), size = 0.8) +
  scale_x_continuous(breaks = seq(0, 50, 5), minor_breaks = seq(0, 50, 5)) +
  scale_y_continuous(labels = function(y) format(y, scientific = TRUE)) +
  xlab('neural networks') +
  ylab(bquote(mean ~ absolute ~ error ~ (k[eff])))

ggsave('fig-13.png', dpi = 320, height = 3.4, width = 6.5)

```

```{r}

df <- read.csv(paste0(source.dir, 'data-set.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df) +


```
