---
title : 'vessel'
output : html_document
---

# vessel.Rmd
#
# William John Zywiec
# The George Washington University
#
# ...

```{r}

# initialize environment
if (!is.null(dev.list())) dev.off()
rm(list = ls())
cat('\014')

```

```{r setup, include = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

# load packages
library(magrittr)

# set variables
dist <- 'gamma'
ensemble.size <- 10

# set source and test directories
source.dir <- 'C:/Users/Will/Dropbox/Dissertation/R/main'
test.dir <- 'E:/test-xxx'

```

```{r}

# load function
source(paste0(source.dir, '/tabulate.R'))

# set working directory
setwd(test.dir)

# tabulate data
data.set <- Tabulate(source.dir)

```

```{r}

# load function
source(paste0(source.dir, '/bn.R'))

# set working directory
setwd('E:/dist')

# build Bayesian network
bn <- BN(dist)

```

```{r}

# load function
source(paste0(source.dir, '/nn.R'))

# set working directory
setwd(test.dir)

# build ensemble model
ensemble.model <- NN(data.set, ensemble.size, source.dir, test.dir)

```

```{r}

# set variables
risk.pool <- 1
sample.size <- 1e+07

# load function
source(paste0(source.dir, '/risk.R'))

bn.data <- list()

# estimate risk
if (sample.size >= 1e+09) {
  risk.pool <- risk.pool * sample.size / 1e+08
  sample.size <- 1e+08
}

for (i in 1:risk.pool) {
  bn.data[[i]] <- Risk(bn, data.set, ensemble.model, ensemble.size, sample.size)
}

# set working directory
setwd(test.dir)

# save Bayesian network data
saveRDS(bn.data, file = paste0('bn-data-', dist, '.RData'))

```
