---
title : 'Plot'
output : html_document
---

# plot.Rmd
#
# William John Zywiec
# The George Washington University
  
```{r setup, include = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(bnlearn)
library(ggplot2)
library(igraph)

data.dir <- 'E:/Dropbox/GWU/Dissertation/data'
fig.dir <- 'E:/Dropbox/GWU/Dissertation/figures'

theme_set(theme_gray() + theme(axis.text = element_text(color = 'black', size = 11), legend.text = element_text(size = 11), text = element_text(color = 'black', family = 'serif', size = 11)))

```

```{r}

setwd(fig.dir)

year <- c(
  1945, 1945, 1945, 1946, 1949, 1950, 1951, 1951, 1952, 1952,
  1952, 1953, 1953, 1954, 1954, 1954, 1955, 1956, 1956, 1957,
  1957, 1958, 1958, 1958, 1958, 1958, 1959, 1960, 1960, 1960,
  1961, 1961, 1962, 1962, 1961, 1961, 1962, 1962, 1963, 1963,
  1963, 1963, 1964, 1965, 1965, 1965, 1965, 1968, 1968, 1968,
  1968, 1970, 1971, 1971, 1978, 1978, 1983, 1997, 1997, 1999)

accident <- c(
  'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor',
  'reactor', 'reactor', 'process', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor', 'reactor',
  'process', 'reactor', 'reactor', 'process', 'process', 'process', 'process', 'reactor', 'reactor', 'process',
  'reactor', 'reactor', 'reactor', 'reactor', 'process', 'process', 'process', 'process', 'reactor', 'reactor',
  'process', 'process', 'process', 'reactor', 'reactor', 'process', 'process', 'reactor', 'reactor', 'reactor',
  'process', 'process', 'reactor', 'reactor', 'process', 'process', 'reactor', 'reactor', 'process', 'process')

country <- c(
  'US', 'US', 'US', 'US', 'US', '--', 'US', 'US', 'US', 'US',
  '--', '--', '--', 'US', 'US', 'US', 'US', 'US', 'US', 'US',
  '--', 'US', '--', 'US', 'US', '--', 'US', 'US', '--', '--',
  'US', 'US', 'US', 'US', 'US', '--', 'US', '--', 'US', '--',
  '--', '--', 'US', 'US', '--', '--', '--', 'US', 'US', '--',
  '--', '--', '--', '--', 'US', '--', '--', '--', '--', '--')

df <- data.frame(year, accident, country)

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = country)) +
  scale_fill_manual(labels = c('outside the United States', 'in the United States'), values = c('gray82', '#6666FF')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5)) +
  theme(legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.title = element_blank()) +
  ylab('criticality accidents')

ggsave('criticality-accidents.png', dpi = 1000, height = 3, width = 6.5)

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = forcats::fct_rev(accident))) +
  scale_fill_manual(labels = c('critical experiments and research reactors', 'production facilities'), values = c('gray82', '#6666FF')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5)) +
  theme(legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.title = element_blank()) +
  ylab('criticality accidents')

ggsave('process-criticality-accidents.png', dpi = 1000, height = 3, width = 6.5)

df <- df[which(df$accident == 'process'), ]

ggplot(df, aes(x = year)) +
  geom_bar(aes(fill = country)) +
  scale_fill_manual(labels = c('outside the United States', 'in the United States'), values = c('gray82', '#6666FF')) +
  scale_x_continuous(breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000), limits = c(1940, 2000)) +
  scale_y_continuous(breaks = c(0:5), minor_breaks = c(0:5), limits = c(0, 5)) +
  theme(legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.title = element_blank()) +
  ylab('criticality accidents') +

ggsave('us-process-criticality-accidents.png', dpi = 1000, height = 3, width = 6.5)

```

```{r}

df <- read.csv(paste0(data.dir, '/uncertainty.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

setwd(fig.dir)

ggplot(df, aes(x = EALF, y = keff, ymin = keff - sd, ymax = keff + sd)) +
  geom_point(size = 0.8) +
  geom_linerange(size = 0.2) +
  geom_smooth(color = 'red', se = FALSE, size = 0.5, span = 0.11) +
  scale_x_log10(breaks = c(1e-07, 1e-06, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1e+00)) +
  scale_y_continuous(breaks = seq(0.98, 1.04, 0.01)) +
  xlab('energy of average neutron lethargy causing fission (MeV)') +
  ylab(bquote(k[eff]))

ggsave('uncertainty.png', dpi = 1000, height = 3.6, width = 6.5)

```

```{r}

library(metR)

df <- read.csv(paste0(data.dir, '/keff-contour-plot.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot(df, aes(x = rad, y = mass, z = keff)) +
  geom_contour2(aes(z = keff), color = 'gray72', size = 0.6) +
  geom_text_contour(aes(z = keff), family = 'serif', size = 3.5, stroke = 0.1) +
  xlab('radius (cm)') +
  ylab('plutonium mass (g)')

ggsave('keff-contour-plot.png', dpi = 1000, height = 3.6, width = 6.5)

```

```{r}

nodes = c('n', 'target\nnucleus', 'fission', 'fission\nproduct', 'fission\nproduct', 'gamma ray', 'n', 'n')

dag <- graph_from_data_frame(
  d = data.frame(
    from = c(1, 2, 3, 3, 3, 3, 3),
    to = c(2, 3, 4, 5, 6, 7, 8)),
  vertices = data.frame(
    id = seq(1, 8),
    label = nodes))

dag.layout <- matrix(
  data = c(
    -.75, 0, 1, 2, 2, 2, 2.5, 2.5,
     0, 0, 0, -0.5, 0.5, 1.1, -0.15, 0.15),
  nrow = 8,
  ncol = 2)

setwd(fig.dir)

pdf(file = 'fission.pdf')
par(mar = rep(1, 4))

plot <- plot(
  dag,
  edge.arrow.size = 0.5,
  edge.color = 'black',
  layout = dag.layout,
  rescale = FALSE,
  vertex.color = c('white', 'white', '#ffda90', 'white', 'white', 'white', 'white', 'white'),
  vertex.frame.color = c('black', 'black', 'black', 'black', 'black', 'white', 'black', 'black'),
  vertex.frame.width = c(1, 1, 10, 1, 1, 1, 1, 1),
  vertex.label.color = 'black',
  vertex.label.family = 'serif',
  vertex.size = c(20, 80, 70, 55, 55, 20, 20, 20),
  xlim = c(-1, 2.75),
  ylim = c(-2, 2))

```

```{r}

setwd(data.dir)

total <- read.csv(paste0(data.dir, '/yield.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot() +
  geom_line(data = total, aes(x = A, y = yield), color = 'blue') +
  xlab('atomic number') +
  ylab('fission product yield (%)') +
  scale_x_continuous(breaks = seq(20, 80, 10), limits = c(20, 75)) +
  scale_y_log10(breaks = c(1e-15, 1e-11, 1e-07, 1e-03, 1e+01), minor_breaks = c(1e-15, 1e-13, 1e-11, 1e-09, 1e-07, 1e-05, 1e-03, 1e-01, 1e+01), limits = c(1e-15, 1e+01))

setwd(fig.dir)

ggsave('yield.png', dpi = 1000, height = 4.8, width = 6.5)

```

```{r}

setwd(data.dir)

total <- read.csv(paste0(data.dir, '/total.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
fission <- read.csv(paste0(data.dir, '/fission.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
elastic <- read.csv(paste0(data.dir, '/elastic.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot() +
  geom_line(data = total, aes(x = energy, y = barns, color = 'total')) +
  geom_line(data = fission, aes(x = energy, y = barns, color = 'fission')) +
  geom_line(data = elastic, aes(x = energy, y = barns, color = 'elastic')) +
  scale_color_manual('', breaks = c('total', 'fission', 'elastic'), labels = c('total (n,tot)', 'fission (n,f)', 'elastic scattering (n,el)'), values = c('#003f5c', '#bc5090', '#ffa600')) +
  scale_x_log10(breaks = c(1e-11, 1e-09, 1e-07, 1e-05, 1e-03, 1e-01, 1e+01, 1e+03)) +
  scale_y_log10(breaks = c(1e-01, 1e+01, 1e+03, 1e+05), minor_breaks = c(1e-01, 1e+00, 1e+01, 1e+02, 1e+03, 1e+04, 1e+05), limits = c(1e-01, 1e+05), labels = function(x) format(x, scientific = TRUE)) +
  xlab('neutron energy (MeV)') +
  ylab(expression(paste(sigma, ' (barns)'))) +
  theme(legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.text.align = 0,
    legend.title = element_blank())

setwd(fig.dir)

ggsave('xs.png', dpi = 1000, height = 4, width = 6.5)

```

```{r}

setwd(data.dir)

angle.1e5 <- read.csv(paste0(data.dir, '/angle-1e5.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
angle.1e6 <- read.csv(paste0(data.dir, '/angle-1e6.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
angle.1e7 <- read.csv(paste0(data.dir, '/angle-1e7.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot() +
  geom_line(data = angle.1e5, aes(x = angle, y = theta, color = '1e+05')) +
  geom_line(data = angle.1e6, aes(x = angle, y = theta, color = '1e+06')) +
  geom_line(data = angle.1e7, aes(x = angle, y = theta, color = '1e+07')) +
  scale_color_manual('incident neutron energy (MeV)', breaks = c('1e+05', '1e+06', '1e+07'), values = c('#003f5c', '#bc5090', '#ffa600')) +
  scale_x_continuous(breaks = seq(0, 180, 30), minor_breaks = seq(0, 180, 30)) +
  scale_y_log10(limits = c(0.003, 100), minor_breaks = c(1e-02, 1e-01, 1e+00, 1e+01, 1e+02)) +
  xlab('scattering angle (degrees)') +
  ylab(expression(paste('d', sigma, 'd', Omega, ' (', theta, ')'))) +
  theme(legend.direction = 'horizontal',
    legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.title = element_text(size = 11)) +
  guides(color = guide_legend(title.position = 'top', title.hjust = 0.5))

setwd(fig.dir)

ggsave('angle.png', dpi = 1000, height = 4.2, width = 6.5)

```

```{r}

setwd(data.dir)

energy.1e6 <- read.csv(paste0(data.dir, '/energy-1e6.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
energy.2e6 <- read.csv(paste0(data.dir, '/energy-2e6.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)
energy.1e7 <- read.csv(paste0(data.dir, '/energy-1e7.csv'), fileEncoding = 'UTF-8-BOM', header = TRUE)

ggplot() +
  geom_line(data = energy.1e6, aes(x = energy, y = mxw, color = '1e-06')) +
  geom_line(data = energy.2e6, aes(x = energy, y = mxw, color = '2e-06')) +
  geom_line(data = energy.1e7, aes(x = energy, y = mxw, color = '3e-06')) +
  scale_color_manual('incident neutron energy (MeV)', breaks = c('1e-06', '2e-06', '3e-06'), values = c('#003f5c', '#bc5090', '#ffa600')) +
  scale_x_log10(breaks = c(1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1e+00, 1e+01), minor_breaks = c(1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1e+00, 1e+01)) +
  scale_y_log10(breaks = c(0.5, 1, 2, 4, 8), minor_breaks = c(0.5, 1, 2, 4, 8), limits = c(0.5, 8)) +
  xlab('neutron energy (MeV)') +
  ylab('ratio to Maxwellian distribution') + # 1.32 MeV
  theme(legend.direction = 'horizontal',
    legend.position = 'top',
    legend.spacing.x = unit(0.2, 'cm'),
    legend.text = element_text(size = 11),
    legend.title = element_text(size = 11)) +
  guides(color = guide_legend(title.position = 'top', title.hjust = 0.5))

setwd(fig.dir)

ggsave('energy.png', dpi = 1000, height = 4.2, width = 6.5)

```

```{r}

nodes <- c('op', 'ctrl', 'mass', 'form', 'mod', 'rad', 'ref', 'thk')

dag <- graph_from_data_frame(
  d = data.frame(
    from = c(rep(1, 7), rep(2, 6)),
    to = c(seq(2, 8), seq(3, 8))),
  vertices = data.frame(
    id = seq(1, 8),
    label = nodes))

dag.layout <- matrix(
  data = c(0, 0, -1.5, -1, -0.5, 0.5, 1, 1.5, 0.8, 0, rep(-0.8, 7)),
  nrow = 8,
  ncol = 2)

setwd(fig.dir)

pdf(file = 'bn.pdf')
par(mar = rep(1, 4))

plot <- plot(
  dag,
  edge.arrow.size = 0.5,
  edge.color = 'black',
  layout = dag.layout,
  rescale = FALSE,
  vertex.color = 'white',
  vertex.label = c(expression(italic('op')),
                   expression(italic('ctrl')),
                   expression(italic('mass')),
                   expression(italic('form')),
                   expression(italic('mod')),
                   expression(italic('rad')),
                   expression(italic('ref')),
                   expression(italic('thk'))),
  vertex.label.color = 'black',
  vertex.label.family = 'serif',
  vertex.size = 40,
  xlim = c(-2, 2),
  ylim = c(-1, 1))

```

```{r}

nodes <- c('op', 'ctrl', 'mass', 'form', 'mod', 'rad', 'ref', 'thk')

dag <- graph_from_data_frame(
  d = data.frame(
    from = c(rep(1, 7), rep(2, 6)),
    to = c(seq(2, 8), seq(3, 8))),
  vertices = data.frame(
    id = seq(1, 8),
    label = nodes))

dag.layout <- matrix(
  data = c(0, 0, -1.5, -1, -0.5, 0.5, 1, 1.5, 0.8, 0, rep(-0.8, 7)),
  nrow = 8,
  ncol = 2)

setwd(fig.dir)

pdf(file = 'moral-graph.pdf')
par(mar = rep(1, 4))

plot <- plot(
  dag,
  edge.arrow.size = 0,
  edge.color = 'black',
  layout = dag.layout,
  rescale = FALSE,
  vertex.color = 'white',
  vertex.label = c(expression(italic('op')),
                   expression(italic('ctrl')),
                   expression(italic('mass')),
                   expression(italic('form')),
                   expression(italic('mod')),
                   expression(italic('rad')),
                   expression(italic('ref')),
                   expression(italic('thk'))),
  vertex.label.color = 'black',
  vertex.label.family = 'serif',
  vertex.size = 40,
  xlim = c(-2, 2),
  ylim = c(-1, 1))

```

```{r}

dag <- graph_from_data_frame(
  d = data.frame(
    from = c(
      rep(1, 3), rep(2, 3),
      rep(3, 4), rep(4, 4), rep(5, 4),
      rep(6, 3), rep(7, 3), rep(8, 3), rep(9, 3),
      rep(10, 2), rep(11, 2), rep(12, 2),
      13, 14),
    to = c(
      rep(seq(3, 5), 2),
      rep(seq(6, 9), 3),
      rep(seq(10, 12), 4),
      rep(c(13, 14), 3),
      rep(15, 2))),
    vertices = data.frame(
      id = seq(1, 15),
      label = c(11, 12, 21, 22, 23, 31, 32, 33, 34, 41, 42, 43, 51, 52, 61)))

dag.layout <- matrix(
  data = c(
    rep(-5, 2), rep(-3, 3), rep(-1, 4), rep(1, 3), rep(3, 2), 5,
    -1, 1,
    -2, 0, 2,
    -3, -1, 1, 3,
    -2, 0, 2,
    -1, 1,
    0),
  nrow = 15,
  ncol = 2)

setwd(fig.dir)

pdf(file = 'nn.pdf')
par(mar = rep(1, 4))

plot(
  dag,
  edge.arrow.size = 0.5,
  edge.color = 'black',
  layout = dag.layout,
  rescale = FALSE,
  vertex.color = 'white',
  vertex.label.color = 'black',
  vertex.label.family = 'serif',
  vertex.size = 80,
  xlim = c(-6, 6),
  ylim = c(-3, 3))

dev.off()

```

```{r}

nodes <- c(1:6)

dag <- graph_from_data_frame(
  d = data.frame(
    from = c(1:5),
    to = c(2:6)),
  vertices = data.frame(
    id = c(1:6),
    label = nodes))

half.tan <- tan(60 * pi / 180) / 4

dag.layout <- matrix(
  c(-2.5, -1.5, -0.5, 0.5, 1.5, 2.5, rep(0, 6)),
  nrow = 6,
  ncol = 2)

setwd(fig.dir)

pdf(file = 'junction-tree.pdf')
par(mar = rep(1, 4))

plot <- plot(
  dag,
  edge.arrow.size = 0,
  edge.color = 'black',
  layout = dag.layout,
  rescale = FALSE,
  vertex.color = 'white',
  vertex.label.cex = 1.2,
  vertex.label.color = 'black',
  vertex.label.family = 'serif',
  vertex.size = 40,
  xlim = c(-3, 3),
  ylim = c(-2, 2))

```

```{r}

theme_set(theme_gray() + theme(axis.text = element_text(color = 'black', size = 11), text = element_text(color = 'black', family = 'serif', size = 11)))

setwd(fig.dir)

z <- c(-2, 0, 2)
y <- c(0, 0, 2)

df <- data.frame(z, y)

ggplot(df, aes(x = z, y = y)) +
  coord_cartesian(xlim = c(-1, 1), ylim = c(0, 1)) +
  geom_line(color = 'black') +
  scale_x_continuous(expression(italic(x)), breaks = 0, expand = c(0, 0), minor_breaks = 0) +
  scale_y_continuous(expression(paste(italic(f(x)), ' = ', italic(max), '{0, ', italic(x), '}')), breaks = 0, expand = c(0, 0), minor_breaks = 0)

ggsave('relu.png', dpi = 1000, height = 2.5, width = 4.5)

```

```{r}

library(gridExtra)

setwd('F:/300/dist')

mass.cpt <- readRDS('mass-gamma.RData')

df1 <- as.data.frame(mass.cpt[[1]][[1]])
df2 <- as.data.frame(mass.cpt[[2]][[1]])
df3 <- as.data.frame(mass.cpt[[3]][[1]])
df4 <- as.data.frame(mass.cpt[[4]][[1]])
df5 <- as.data.frame(mass.cpt[[5]][[1]])
df6 <- as.data.frame(mass.cpt[[6]][[1]])

x <- c(0:4000)

colnames(df1) <- colnames(df2) <- colnames(df3) <- colnames(df4) <- colnames(df5) <- colnames(df6) <- ('y')

# probability distribution plots
p1 <- ggplot(df1, aes(x, y)) + ggtitle('large sample') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

p2 <- ggplot(df2, aes(x, y)) + ggtitle('machining') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

p3 <- ggplot(df3, aes(x, y)) + ggtitle('metallurgy') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

p4 <- ggplot(df4, aes(x, y)) + ggtitle('small sample') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

p5 <- ggplot(df5, aes(x, y)) + ggtitle('solution') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

p6 <- ggplot(df6, aes(x, y)) + ggtitle('waste') + geom_line() + scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) + scale_y_continuous(breaks = c(0, 0.025, 0.05, 0.075), limits = c(0, 0.075)) + theme(plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) + xlab('plutonium mass (g)') + ylab('P(plutonium mass)')

grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2)

setwd(fig.dir)

ggsave('gamma.png', plot = grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2), dpi = 2000, height = 3.8, width = 6.3)

```

```{r}

library(fitdistrplus)
library(gridExtra)

setwd('F:/300/dist')

# Q-Q plots
a1 <- read.csv('mass-a-1.csv', header = TRUE)
a2 <- read.csv('mass-a-2.csv', header = TRUE)
a3 <- read.csv('mass-a-3.csv', header = TRUE)
a4 <- read.csv('mass-a-4.csv', header = TRUE)
a5 <- read.csv('mass-a-5.csv', header = TRUE)
a6 <- read.csv('mass-a-6.csv', header = TRUE)

fit1 <- qqcomp(fitdist(a1[[1]], 'norm'), plotstyle = 'ggplot')
fit2 <- qqcomp(fitdist(a2[[1]], 'norm'), plotstyle = 'ggplot')
fit3 <- qqcomp(fitdist(a3[[1]], 'norm'), plotstyle = 'ggplot')
fit4 <- qqcomp(fitdist(a4[[1]], 'norm'), plotstyle = 'ggplot')
fit5 <- qqcomp(fitdist(a5[[1]], 'norm'), plotstyle = 'ggplot')
fit6 <- qqcomp(fitdist(a6[[1]], 'norm'), plotstyle = 'ggplot')

p1 <- ggplot(fit1$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('large sample') +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

p2 <- ggplot(fit2$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('machining') +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

p3 <- ggplot(fit3$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('metallurgy') +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

p4 <- ggplot(fit4$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('small sample') +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

p5 <- ggplot(fit5$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('solution') +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

p6 <- ggplot(fit6$data, aes(values, sdata)) +
  geom_abline(color = '#bc5090', intercept = 0, size = 0.7, slope = 1) +
  geom_point(shape = 20, size = 0.8, color = 'black') + ggtitle('waste') +
  scale_x_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  scale_y_continuous(breaks = c(0, 20, 40, 60), limits = c(0, 70)) +
  theme(legend.position = 'none', plot.title = element_text(face = 'bold', hjust = 0.5, size = 11)) +
  xlab('theoretical quantiles') +
  ylab('empirical quantiles')

grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2)

setwd(fig.dir)

ggsave('qq.png', plot = grid.arrange(p1, p2, p3, p4, p5, p6, nrow = 2), dpi = 2000, height = 3.8, width = 6.3)

```
