---
title : 'R Notebook'
output : html_document
---

# notebook.Rmd
#
# William John Zywiec
# The George Washington University

```{r, include = FALSE, warning = FALSE}

# initialize environment
if (!is.null(dev.list())) dev.off()
rm(list = ls())
cat('\014')

```

```{r, setup, include = FALSE, warning = FALSE}

# set variables
code <- 'mcnp'
home.dir <- 'C:/Users/X/Documents/dissertation' # modify this path
source.dir <- paste0(home.dir, '/source') # directory that contains all source files
data.dir <- paste0(home.dir, '/data') # directory that contains MCNP data (build/linux)

```

```{r, warning = FALSE}

# load function
source(paste0(source.dir, '/tabulate.R'))

# tabulate data
dataset <- Tabulate(code, source.dir, data.dir)

```

```{r, warning = FALSE}

# set variables
batch.size <- 8192
ensemble.size <- 15 # 15
epochs <- 1500 # 1500
layers <- '8192-256-256-256-256-16'
loss <- 'sse'
opt.alg <- 'adamax'
learning.rate <- 0.00075
replot <- TRUE
test.dir <- paste0(home.dir, '/test/', loss) # directory that contains model files
val.split <- 0.2

# load function
source(paste0(source.dir, '/nn.R'))

# build metamodel
metamodel <- NN(dataset, batch.size, ensemble.size, epochs, layers, loss, opt.alg, learning.rate, replot, val.split, source.dir, test.dir)

```

```{r, warning = FALSE}

# set variables
dist <- 'normal'
risk.pool <- 100
dist.dir <- paste0(home.dir, '/dist') # directory that contains fitted distribution data

if (dist == 'normal') {
  sample.size <- 1e+10
} else if (dist == 'gamma' || dist == 'weibull') {
  sample.size <- 1e+08
} else if (dist == 'log-normal') {
  sample.size <- 1e+07
}

# load functions
source(paste0(source.dir, '/bn.R'))
source(paste0(source.dir, '/risk.R'))

# build Bayesian network
bn <- BN(dist, dist.dir)

# estimate risk
risk <- Risk(bn, dataset, metamodel, risk.pool, sample.size, source.dir, test.dir)

```
